### ISSUE TITLE
Commit 442dd81 makes some apps think that password/fingerprint unlock have changed after reboot

### ISSUE THREAD

**Issue by saitama-droid** [beakthoven/TrickyStoreOSS#31]
Device: Poco F6 (peridot)
ROM: Stock (HyperOS 2.0.204.0)
Tricy-Store-OSS: v2.1.0-60-442dd81-release

Description:

Whenever I reboot system, for instance after having updated the module to this version, some apps logout or ask for face ID verification saying that either password or fingerprint unlock has been changed.

I have tested this issue and narrowed it down to commit 442dd81. All worked well when I reverted to v2.1.0-59-29194b6-release.

I attached screenshots of the module section on KSU Next, Instagram and Mercado Pago.

Mercago Pago translation is: we have noticed changes on your fingerprint unlock settings, use face ID to access your account.

![Image](https://github.com/user-attachments/assets/6a977bfd-4236-4878-88e8-46bc490d350a)
![Image](https://github.com/user-attachments/assets/8cdbeb85-a2cc-47a3-9774-c895bd176ce4)
![Image](https://github.com/user-attachments/assets/2af5d9cc-de09-44d9-a83a-8b6178fc3b2b)

**Comment by saitama-droid** [comment]
> Well it's because you have added unnecessary apps like Instagram on your target.txt but anyways [442dd81](https://github.com/beakthoven/TrickyStoreOSS/commit/442dd815e798a687fd787d0e34344c7e31bae799) was introduced to fix a issue specific to key attestation app... I guess it's better to limit the clearing to that app until we find a better way.
> 
> Please try this build
> 
> [Tricky-Store-OSS-v2.1.0-62-8d0e745-Release.zip](https://github.com/user-attachments/files/22101001/Tricky-Store-OSS-v2.1.0-62-8d0e745-Release.zip)

I did a new test: removed the apps from target.txt, updated the module to the v2.1.0-62-8d0e745 and rebooted. Instagram worked fine but Mercado Pago showed the same error as before.

**Comment by aolik08** [comment]
> > > Well it's because you have added unnecessary apps like Instagram on your target.txt but anyways [442dd81](https://github.com/beakthoven/TrickyStoreOSS/commit/442dd815e798a687fd787d0e34344c7e31bae799) was introduced to fix a issue specific to key attestation app... I guess it's better to limit the clearing to that app until we find a better way.
> > > Please try this build
> > > [Tricky-Store-OSS-v2.1.0-62-8d0e745-Release.zip](https://github.com/user-attachments/files/22101001/Tricky-Store-OSS-v2.1.0-62-8d0e745-Release.zip)
> > 
> > 
> > Makes sense. I'll select only necessary apps from now on. The behavior is the same on v2.1.0-62-8d0e745
> 
> Is it? The build I provided might have the same version but it's a local build with some changes to limit keystore clearing to key attestation app.

I had the same issue, every time I rebooted the phone, with Revolut app, My Toyota, some local taxi app and a few others. I mean after reboot the applications kept crashing until I cleared app data and relogin, but with this version I am unable to reproduce it, at least with Revolut app. The other apps I have removed them from target.txt
Device Galaxy s24 ultra SM-S928B
ROM stock S928BXXS4BYH2
magisk alpha, play integrity fork, rezygisk, vbmeta fixer by reveny, zygisk assistant, lsposed by JingMatrix, HMAL
Thanks

**Comment by beakthoven** [comment]
The problematic commit has been reverted and the issue that it intended to fix has been fixed in another way as of https://github.com/beakthoven/TrickyStoreOSS/commit/40855075ad164de58b0d7411c1c83d648f496df9

**Comment by zedocrob** [comment]
[Tricky-Store-OSS-v2.1.0-67-8625be6-Release](https://github.com/beakthoven/TrickyStoreOSS/actions/runs/17457402942/artifacts/3924685126) seems to have solved the problem for me

**Comment by beakthoven** [comment]
> > The problematic commit has been reverted and the issue that it intended to fix has been fixed in another way as of [4085507](https://github.com/beakthoven/TrickyStoreOSS/commit/40855075ad164de58b0d7411c1c83d648f496df9)
> 
> it is still not working, almost the same behaviour as in v2.1.0-60-442dd81-release, with a little twist: i am unable to open revolut app even after removing all data. the app starts and then crashes

Are you sure because the problematic commits have been reverted

**Comment by aolik08** [comment]
> > > > The problematic commit has been reverted and the issue that it intended to fix has been fixed in another way as of [4085507](https://github.com/beakthoven/TrickyStoreOSS/commit/40855075ad164de58b0d7411c1c83d648f496df9)
> > > 
> > > 
> > > it is still not working, almost the same behaviour as in v2.1.0-60-442dd81-release, with a little twist: i am unable to open revolut app even after removing all data. the app starts and then crashes
> > 
> > 
> > Are you sure because the problematic commits have been reverted
> 
> Yes, I was unable to open revolut app, using 2.1.0-67, on 2 samsung galaxy phones S20-android 13 and S24-android 15. On S24 i have removed the app data, on S20 not. On S24 reverting to the old local created version shared in this thread it required me to choose account to login to, on S20 reverting to the same version asked for the password, as if nothing happened. Maybe something remained in android cache? I will test further in the morning.

Nope it still not working but on android 15, rolling back from v2.1.0-67 to 2.1.0-62 local, to be able to relogin i had to clear app data to be able to use the app again. It does not matter if i remove the app data or not on 67, the app still crashes, untill.rolling back and removing the data on 62 local

**Comment by aolik08** [comment]
@zedocrob, the problem still exists for the apps that are added to the target.txt in ! mode
